# Generated by Django 3.0.5 on 2021-04-28 05:55

from django.db import migrations, models
import djongo.models.fields
import query.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsihoTest',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('questions', djongo.models.fields.ArrayField(model_container=query.models.Question)),
            ],
        ),
    ]
