# Generated by Django 3.2 on 2021-06-02 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedtest',
            options={'ordering': ['-data']},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_assign', models.ManyToManyField(blank=True, to='query.AssignedTest')),
                ('user_test', models.ManyToManyField(blank=True, to='query.PsihoTest')),
            ],
        ),
    ]
