# Generated by Django 3.0.5 on 2021-04-29 04:45

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_assignedtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtest',
            name='answer',
            field=djongo.models.fields.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedtest',
            name='psihotest',
            field=models.CharField(default='6088f92bdd434054ced8b9fb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psihotest',
            name='total_rules',
            field=djongo.models.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
