# Generated by Django 3.2 on 2021-05-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20210505_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtest',
            name='answer',
        ),
        migrations.AlterField(
            model_name='assignedtest',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='query.answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='query.question')),
            ],
        ),
        migrations.AddField(
            model_name='assignedtest',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, to='query.AnswerTest'),
        ),
    ]
