# Generated by Django 3.2 on 2021-06-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20210605_2042'),
        ('query', '0003_auto_20210607_1127'),
    ]

    operations = [
    ]
