# Generated by Django 3.2 on 2021-05-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20210509_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-text']},
        ),
    ]
